# Data volumes defined in these services (which must be defined in child templates):
# dogecoin-data
# dogeparty-data
# dogeblock-data
# armory-data
# mongodb-data

services:
  dogecoin-base:
    build:
      context: ./extras/docker/dogecoin
    volumes:
      - ./config/dogecoin:/root/.dogecoin-config
      - dogecoin-data:/root/.dogecoin/
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"

  dogecoin-base-mainnet:
    hostname: ${HOSTNAME_BASE}-dc
    extends:
      service: dogecoin-base
    ports:
      - "8335:8335"
      - "28835:28835"
    environment:
      - PARAMS=-conf=/root/.dogecoin-config/dogecoin.conf

  dogecoin-base-testnet:
    hostname: ${HOSTNAME_BASE}-dc-t
    extends:
      service: dogecoin-base
    ports:
      - "18335:18335"
      - "38835:38835"
    environment:
      - PARAMS=-conf=/root/.dogecoin-config/dogecoin.testnet.conf

  addrindexrs-dc-base:
    build:
      context: ./src/addrindexrs-dc
      dockerfile: ./Dockerfile
    command: cargo run --release -- -vvvv
    volumes:
      - ./config/addrindexrs-dc:/root/.config/addrindexrs-dc
      - addrindexrs-dc-data:/home/user/db/
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    environment:
      - ADDRINDEXRS_JSONRPC_IMPORT=1
      - ADDRINDEXRS_TXID_LIMIT=15000
      - "ADDRINDEXRS_COOKIE=rpc:rpc"

  addrindexrs-dc-base-mainnet:
    hostname: ${HOSTNAME_BASE}-idxd
    extends:
      service: addrindexrs-dc-base
    ports:
      - "8435:8435"
    environment:
      - "ADDRINDEXRS_INDEXER_RPC_ADDR=0.0.0.0:8435"
      - "ADDRINDEXRS_DAEMON_RPC_ADDR=dogecoin:8335"

  addrindexrs-dc-base-testnet:
    hostname: ${HOSTNAME_BASE}-idxd-t
    extends:
      service: addrindexrs-dc-base
    ports:
      - "18435:18435"
    environment:
      - "ADDRINDEXRS_INDEXER_RPC_ADDR=0.0.0.0:18435"
      - ADDRINDEXRS_NETWORK=testnet
      - "ADDRINDEXRS_DAEMON_RPC_ADDR=dogecoin-testnet:18335"

  dogeparty-base:
    build:
      context: ./src/dogeparty-lib
    volumes:
      - ./config/dogeparty:/root/.config/dogeparty
      - dogeparty-data:/root/.local/share/dogeparty
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"

  dogeparty-base-mainnet:
    hostname: ${HOSTNAME_BASE}-dp
    extends:
      service: dogeparty-base
    ports:
      - "4005:4005"
    environment:
      - PARAMS=--config-file=/root/.config/dogeparty/server.conf
      - DOGE_NETWORK=mainnet
      - NO_BOOTSTRAP=${NO_BOOTSTRAP}
      
  dogeparty-base-testnet:
    hostname: ${HOSTNAME_BASE}-dp-t
    extends:
      service: dogeparty-base
    ports:
      - "14005:14005"
    environment:
      - PARAMS=--config-file=/root/.config/dogeparty/server.testnet.conf
      - DOGE_NETWORK=testnet
      - NO_BOOTSTRAP=${NO_BOOTSTRAP}

  dogeblock-base:
    build:
      context: ./src/dogeblock
    volumes:
      - ./config/dogeblock:/root/.config/dogeblock
      - dogeblock-data:/root/.local/share/dogeblock
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"

  dogeblock-base-mainnet:
    hostname: ${HOSTNAME_BASE}-cb
    extends:
      service: dogeblock-base
    ports:
      - "4105:4105"
    environment:
      - PARAMS=--config-file=/root/.config/dogeblock/server.conf

  dogeblock-base-testnet:
    hostname: ${HOSTNAME_BASE}-cb-t
    extends:
      service: dogeblock-base
    ports:
      - "14105:14105"
      - "14106:14106"
      - "14107:14107"
    environment:
      - PARAMS=--config-file=/root/.config/dogeblock/server.testnet.conf

  dogewallet-base:
    hostname: ${HOSTNAME_BASE}-dw
    build:
      context: ./src/dogewallet
    volumes:
      - ./config/dogewallet/ssl:/ssl_config
      - dogeblock-data:/dogeblock_data
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    ports:
      - "80:80"
      - "443:443"

  mongodb-base:
    hostname: ${HOSTNAME_BASE}-mongo
    image: mongo:3.2
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    ports:
      - ${MONGODB_HOST_INTERFACE}:27017:27017

  redis-base:
    hostname: ${HOSTNAME_BASE}-redis
    image: redis:3.2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"

  http-addrindexrs-dc-base:
    build:
      context: ./src/http-addrindexrs-dc
    volumes:
      - ./config/http-addrindexrs-dc:/root/.config/http-addrindexrs-dc      
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"

  http-addrindexrs-dc-base-mainnet:
    hostname: ${HOSTNAME_BASE}-hadc
    extends:
      service: http-addrindexrs-dc-base
    ports:
      - "8096:8096"
    environment:
      - DOTENV_CONFIG_PATH=/root/.config/http-addrindexrs-dc/server.conf
      
  http-addrindexrs-dc-base-testnet:
    hostname: ${HOSTNAME_BASE}-hadc-t
    extends:
      service: http-addrindexrs-dc-base
    ports:
      - "18096:18096"
    environment:
      - DOTENV_CONFIG_PATH=/root/.config/http-addrindexrs-dc/server.testnet.conf    

  xdp-proxy-base:
    build:
      context: ./src/xdp-proxy
      dockerfile: ./Dockerfile
    volumes:
      - ./config/xdp-proxy:/root/.config/xdp-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "30"
    environment:
      - INTERVAL_CHECK_DOGEPARTY_PARSED=1000

  xdp-proxy-base-mainnet:
    hostname: ${HOSTNAME_BASE}-prx
    extends:
      service: xdp-proxy-base
    ports:
      - "8095:8095"
    environment:
      - HTTP_PORT=8095
      - ADDRINDEXRS_URL=tcp://addrindexrs:8435
      - BITCOIN_ZMQ_URL=tcp://bitcoin:28835
      - REDIS_URL=redis://redis:6379/8
      - SECRETS_PATH=/root/.config/xdp-proxy/secrets

  xdp-proxy-base-testnet:
    hostname: ${HOSTNAME_BASE}-prx-t
    extends:
      service: xdp-proxy-base
    ports:
      - "18095:18095"
    environment:
      - HTTP_PORT=18095
      - ADDRINDEXRS_URL=tcp://addrindexrs-testnet:18435
      - BITCOIN_ZMQ_URL=tcp://bitcoin-testnet:38835
      - REDIS_URL=redis://redis:6379/9
      - SECRETS_PATH=/root/.config/xdp-proxy/secrets-testnet

volumes:
  dogecoin-data:
  addrindexrs-dc-data:
